---
- hosts: all
  remote_user: centos
  become: false

  tasks:
  - name: Create genconf directory
    file:
      dest: /home/centos/genconf
      state: directory
      mode: 0755

  - name: Distribute ip-detect script
    copy:
      src: ../files/ip-detect-aws
      dest: /home/centos/genconf/ip-detect

  - name: Create /tmp/dcos
    file:
      dest: /tmp/dcos
      state: directory
      mode: 0755
