---
- hosts: all
  remote_user: centos
  become: false

  tasks:
  - name: Create genconf
    file:
      path: /home/centos/genconf
      state: directory
      mode: 0755

  - name: Distribute ip-detect
    copy:
      src: ../files/ip-detect-aws
      dest: /home/centos/genconf/ip-detect

- hosts: bootstrap
  remote_user: centos
  become: false

  tasks:
  - name: Generate and write out DC/OS config.yaml
    template:
      src: ../files/config.yaml.j2
      dest: /home/centos/genconf/config.yaml

  - name: Fetch DC/OS installer from Mesosphere
    get_url:
      url: https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh
      dest: /home/centos

  - name: Generate DC/OS install bits
    become: true
    shell: bash /home/centos/dcos_generate_config.sh

  - name: Start nginx Docker container
    become: true
    docker_container:
      name: nginx
      image: nginx:latest
      ports:
      - "80:80"
      volumes:
      - "/home/centos/genconf/serve:/usr/share/nginx/html:ro"

- hosts: dcos-cluster
  remote_user: centos
  become: false

  tasks:
  - name: Create /tmp/dcos
    file:
      path: /tmp/dcos
      state: directory
      mode: 0755

  - name: Fetch DC/OS installer
    get_url:
      url: http://{{ hostvars[groups['bootstrap'][0]].ansible_eth0['ipv4']['address'] }}/dcos_install.sh
      dest: /tmp/dcos

- hosts: masters
  remote_user: centos
  become: true

  tasks:
  - name: Installation of master nodes
    async: 600
    poll: 0
    shell: bash /tmp/dcos/dcos_install.sh master

- hosts: public-agents
  remote_user: centos
  become: true

  tasks:
  - name: Installation of public agents
    async: 600
    poll: 0
    shell: bash /tmp/dcos/dcos_install.sh slave_public

- hosts: private-agents
  remote_user: centos
  become: true

  tasks:
  - name: Installation of private agents
    async: 600
    poll: 0
    shell: bash /tmp/dcos/dcos_install.sh slave
